### ISSUE TITLE
1.9.2 spigot - Latest battlearena update still has this issue  BattleArena v3.9.10.10

### ISSUE THREAD

**Issue by tara81** [BattlePlugins/BattleArena#71]
http://pastebin.com/CBaAM7Fu
players cannot leave arena

**Comment by Europia79** [comment]
I just tested BattleArena... and i could leave the arena just fine.

**Comment by tara81** [comment]
https://github.com/BattlePlugins/BattleArena/issues/67
It doesn't happen 100% of the time.

It happens to one in 30 players(roughly).  Keep leaving and rejoining about 200 times and it might happen.

**Comment by tara81** [comment]
I'm pretty sure the Errors mean something.  Please do not dissmiss this because I had to turn off battlearena until you guys correct this.

**Comment by tara81** [comment]
http://pastebin.com/KzH7if5Y

**Comment by Europia79** [comment]
That formatted log file is so much easier to read than the console output.

I fixed the error... hopefully it'll also fix the arena leave issue too (if they're related).
http://rainbowcraft.sytes.net/download/plugins/BattleArena/v3.9.10.10/

Lemme know if this is fixed and i'll upload it to dev.bukkit

**Comment by tara81** [comment]
Just started testing it, will get back to you soon ! THANK you so much for this I hope it works !

**Comment by tara81** [comment]
ERRRORS still happening and players are still stuck:
http://pastebin.com/dJrUDmUk
http://pastebin.com/su2hZdCd

**Comment by tara81** [comment]
Please don't give up

**Comment by RednedEpic** [comment]
Please direct any comments intended for this Issue to #56.
